### PR TITLE
change backButton to closeButton

### PR DESCRIPTION
**Pull request by LisaL26**
The closeButton image is a screenshot of our figma file. Is it okay to use this?

### CODE REVIEW

**Comment by stapps21** [comment]
Please place the close button like in the Figma Wireframe (top right)
The other overlay, which is currently on the top right, can be removed - we don't need it anymore.
Thanks :)

**Comment by stapps21** [comment]
> The closeButton image is a screenshot of our figma file. Is it okay to use this?

It would be better if you use an close icon (so only the white "x") and give the button a background-color. 😄

**Comment by LisaL26** [comment]
> > The closeButton image is a screenshot of our figma file. Is it okay to use this?
> 
> It would be better if you use an close icon (so only the white "x") and give the button a background-color. 😄

Yes, sure. Which library should be used for the icons? For example font awesome or something like that? :)

**Comment by stapps21** [comment]
> > > The closeButton image is a screenshot of our figma file. Is it okay to use this?
> > 
> > 
> > It would be better if you use an close icon (so only the white "x") and give the button a background-color. 😄
> 
> Yes, sure. Which library should be used for the icons? For example font awesome or something like that? :)

Please ask @anniekolb for that. I am currently not aware if a icon library is used or if the icons get imported independently.

**Pull request merged**
