### PR TITLE
147 rethink the current solutions of how audios are played

### PR DESCRIPTION
**Pull request by stapps21**
Using Web Audio API (AudioContext) instead of HTMLAudioElement for sounds:
- **No Delay:** Audios should now play without any delay.
- **Smooth Looping:** Looped audios should no longer have gaps.
- **Fixed onEndCallback:** The onEndCallback for audios should now work as expected.
- Fixed further audio bugs

**The mascot is still using HTMLAudioElement**, but the issue where the audio didn't play during onboarding on the first start should now be fixed. I’ve **removed SpeechSynthesis**, so only pre-recorded audios will be used from now on and an error is provided, when the audio is missing instead of using SpeechSynthesis as fallback.

### CODE REVIEW

**Comment by stapps21** [comment]
Here's a revised version of your comment:

---

We're now using `AudioContext` instead of `HTMLAudioElement`, which should resolve several issues. Audios should play without any delays, and audio loops should now function correctly on iPads as well.

@pascall2 @JuliusBeutel, could you please test all the sounds, particularly on the iPad, to ensure everything is working smoothly? Let me know if you notice anything unusual.

Thanks!

**Comment by pascall2** [comment]
I think almost every works as expected.

There are some minor problems a problem in the caretime minigame: 
* For me, too many sounds are played at once for the soap bubbles
* Only on the iPad: The shower sound is strange on an won't stop playing

Is there a specific reason why you removed the option to play the mascot messages again?

**Review by pascall2 — COMMENTED** [review]
I think almost everything works as expected.

There are some minor problems in the caretime minigame:
* For me, too many sounds are played at once for the soap bubbles
* Only on the iPad: The shower sound is strange and won't stop playing

Is there a specific reason why you removed the option to play the mascot messages again?

**Comment by stapps21** [comment]
Thank you for your feedback! I'll review your suggestions and work on addressing the issues.

> Is there a specific reason why you removed the option to play the mascot messages again?

It seems I might have removed it during the refactoring process and overlooked re-implementing it.
I was also a bit unclear about its intended functionality: was it supposed to repeat the last message spoken, or should the mascot provide the explanation of the game again when clicked?

I'll make sure to reintroduce this feature accordingly.

**Comment by pascall2** [comment]
> was it supposed to repeat the last message spoken, or should the mascot provide the explanation of the game again when clicked?

It was there to repeat the last message. Of course in terms of usability it was not exactly obvious to click on the mascot.

**Comment by stapps21** [comment]
> For me, too many sounds are played at once for the soap bubbles

I could not reproduce this. For me always when a bubble gets created a single sound is played.
Or do you mean that when there are multiple bubbles generated that there are too many sounds and I should reduce it, so not every bubble has a sound when it gets created?

P.S.: The other bug should be fixed and the mascot should repeat the last message when clicked on it, would be nice to have a review of you again.

**Comment by stapps21** [comment]
To address a browser warning, I modified the initialization of `AudioContext` so that it occurs when `playSound` is called, rather than directly when creating an instance of `useAudioManager`. This change ensures that the `AudioContext` is only initialized upon user interaction (specifically, when the `playSound` function is first called, such as on the initial click of the PetCard component). 

While this approach may introduce a slight delay in playing the "click" sound on the first PetCard click  (or not playing it at all on iPad), it adheres to best practices by avoiding unnecessary browser warnings.

**Review by JuliusBeutel — APPROVED** [review]

**Pull request merged**
